import: definition.yaml

concurrency:
  task:
    # css-std: 5
    # omnigibson-std: 4
    minecraft-std: 4
  agent:
    gpt-4o-2024-05-13: 4

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-4o-2024-05-13
    task:
      # - css-std
      # - omnigibson-std
      - minecraft-std

# output: "outputs/{TIMESTAMP}"
# output: "outputs/css_test"
# output: "outputs/omnigibson"
output: "outputs/minecraft"
